### PR TITLE
Update react, add mofo-ui, remove some warnings

### PR DESCRIPTION
**Pull request by alanmoo**

### CODE REVIEW

**Comment by alanmoo** [comment]
@kristinashu @hannahkane @mmmavis can I get some eyes on the deployment to make sure it looks good still? I'm upgrading some libraries so this is kind of going to have to be [like this](https://media.giphy.com/media/zuIdDDGH581q/giphy.gif). It might not be exactly the same, but let's make sure it still looks decent and nothing breaks.

**Comment by kristinashu** [comment]
Nice gif! Styling wise everything looks good to me.

I am noticing it's doing that react thing where when I navigate to a new page, it doesn't bring me to the top of the browser. Example, if I scroll down to the footer and click between About/Festival Team/Participation Guidelines I'm are at the bottom of the page (should be at the top).

**Comment by mmmavis** [comment]
@alanmoo looks great on iPhone!

**Comment by hannahkane** [comment]
yeah, looks good to me, too

**Comment by alanmoo** [comment]
Good catch, @kristinashu! I'll take care of that and if the code looks good, @mmmavis, I'll merge this in so we can use it as a new base for changes.

**Pull request merged**
