### PR TITLE
Added Space icons

### LINKED ISSUE #463: Add Space icons
See https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/106 for details

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #463 
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/106

### CODE REVIEW

**Comment by mmmavis** [comment]
@kristinashu review plz? https://mozillafestival-org-sta-pr-464.herokuapp.com/spaces-and-sessions 😄

**Comment by kristinashu** [comment]
Some of the icons, like Localisation and Demystify the Web, look too small. Can you make them bigger?

**Comment by mmmavis** [comment]
@kristinashu I adjusted some icon sizes. Let me know what you think: https://mozillafestival-org-sta-pr-464.herokuapp.com/spaces-and-sessions 😉

**Comment by kristinashu** [comment]
Perfecto, thanks!

**Comment by mmmavis** [comment]
🚢 ing it now!

**Pull request merged**
