### PR TITLE
Update Kevin's title

### PR DESCRIPTION
**Pull request by alanmoo**

### CODE REVIEW

**Comment by mmmavis** [comment]
relates to https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/87#issuecomment-246468778

r+ ✨

**Comment by edrushka** [comment]
How do I see this to review? Is it on staging somewhere?

**Comment by alanmoo** [comment]
Oops, I merged it in to staging but didn't deploy. It's at https://mozillafestival-org-staging.herokuapp.com/team and I'll deploy in the morning.

**Comment by edrushka** [comment]
Looks good on staging! Sorry - I just meant to comment above, but I think I accidentally merged it.

**Comment by alanmoo** [comment]
Nope, it was me that did it, says so right above your comment :)

**Pull request merged**
