### PR TITLE
Add Marc Bio

### PR DESCRIPTION
**Pull request by alanmoo**
Reduce padding on team page because of narrow text columns

Closes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/83

@sabrinang I reduced the padding between profiles to 10px from 15px- the text was wrapping way too much. Please take a look at the review deploy and lmk if that works.

### CODE REVIEW

**Comment by mmmavis** [comment]
will review this after im back from my quick lunch 🍴

**Comment by mmmavis** [comment]
R+ Looks good to me. We can merge this after @sabrinang has okayed on the padding tweaks. 🎉

**Comment by alanmoo** [comment]
Since this wasn't merged yet, I added Kevin's bio (and reverted the 15px change.)

@mmmavis can I get one more review?

**Comment by mmmavis** [comment]
looking great! r+

**Pull request merged**
