### PR TITLE
timeblock adjustment

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/115#issuecomment-254206677

### CODE REVIEW

**Comment by mmmavis** [comment]
@alanmoo mind taking a look at this tiny PR?

**Comment by mmmavis** [comment]
nice catch. thanks @alanmoo ! I'll shrink font size and padding a bit for mobile as a quick fix.

**Comment by alanmoo** [comment]
👍 good quick-win.

**Comment by mmmavis** [comment]
🍻

**Pull request merged**
