### PR TITLE
Project page

### PR DESCRIPTION
**Pull request by alanmoo**
@cadecairos

### CODE REVIEW

**Comment by alanmoo** [comment]
@xmatthewx

**Comment by xmatthewx** [comment]
@kristinashu recommends that we left align the Visit button. 

@alanmoo – A few new projects landed on Sunday & Monday after this list was made. I'd also like to move a few projects to the top of the list to feature them. I'll share with you.

**Comment by gvn** [comment]
The images could really use some optimization:

screen shot 2016-11-07 at 11 26 13 am

**Comment by alanmoo** [comment]
Ah, yeah; I crushed the largest one (which was in the MB) when I was rushing to complete this at MozFest but now that I have more time I'll run them through something.

**Comment by gvn** [comment]
ImageOptim and ImageAlpha are both quite nice if you don't have them!

**Comment by xmatthewx** [comment]
Good catch. I shrunk a bunch that came in early, but forgot to check post festival. Oops.

**Comment by xmatthewx** [comment]
👍

**Comment by alanmoo** [comment]
Closes #482

**Pull request merged**
