### PR TITLE
Speakers page

### LINKED ISSUE #685: Create Speakers page
We need a place on the site to highlight 2017 speakers and 2016 archived talks. 

Wondering if it makes sense to use the [Team Page](https://mozillafestival.org/team) as a template, and have tabs for each year (let's design this assuming speaker series will continue in 2018 and beyond).

Content for 2017 is already written in the [blog](https://medium.com/mozilla-festival/journalists-activists-hackers-meet-this-years-mozfest-speakers-89018c7d2c97). Content for 2016, including links to talks, could be easily compiled. 

Note that if we built a dedicated page, 2016 speakers should come off the landing page.

What do you think @mmmavis @hannahkane @KevZawacki @Saallen

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #685

### CODE REVIEW

**Comment by mmmavis** [comment]
@edrushka I've removed the 2016 Speakers section from the homepage and added a /speakers page. See my progress: https://mozillafestival-org-sta-pr-708.herokuapp.com/speakers Do we wanna add some description to each talk? That page looks a bit bare. Two other questions - 1) where do we want the 2017 speakers info to go? 2) how do we wanna feature the speakers page? (as a nav link? footer link? or?)

/cc @sabrinang

**Comment by edrushka** [comment]
@mmmavis 
- 2016 and 2017 should each have their own tab (like the Team page)
- The title on the hero banner can just be "speakers"
- Is there room on the top nav for a link that says "speakers"? I'd put it between Spaces and What to Expect.

@KevZawacki do we have descriptions for each of the 2016 talks anywhere? Please give any other feedback you have on Mavis' staging link above.

**Comment by KevZawacki** [comment]
@mmmavis @edrushka The page looks great! 

Re: talk descriptions, let's replace the current text beneath speakers' Twitter handles with the YouTube description text. You can find the YouTube description text [here](https://www.youtube.com/playlist?list=PLYiaJo7rYNXLQSEAa2RdyyiS28Ke2Rl60) — click an individual video and see the copy beneath. 

So on the MozFest.org D&D page,

Zeynep Tufekci
@zeynep
Professor, University of North Carolina. Contributor, New York Times

becomes

Zeynep Tufekci
@zeynep
Zeynep Tufekci is a professor and author specializing in the intersection of technology and society. She spoke at MozFest 2016 about social media platforms, inclusion and exclusion online. 

and so on.

**Comment by mmmavis** [comment]
@KevZawacki @edrushka cool thanks for the feedback! 🍰 🍰 🍰

**Comment by mmmavis** [comment]
@edrushka mind reviewing https://mozillafestival-org-sta-pr-708.herokuapp.com/speakers ?

**Comment by edrushka** [comment]
This looks great! R+ from me. @KevZawacki do you want to take a final look?

**Comment by KevZawacki** [comment]
@mmmavis @edrushka Speaker page looks beautiful! :1st_place_medal:

**Comment by mmmavis** [comment]
🍾 :clinking_glasses: :clinking_glasses: :clinking_glasses:

**Pull request merged**
