### PR TITLE
CFP Close 2018

### LINKED ISSUE #1007: Home page: Implement Updates
Please update https://mozillafestival.org/ based on revised design mockups based in issue: https://github.com/mozilla/mozillafestival.org/issues/962

### PR DESCRIPTION
**Pull request by mmmavis**
https://github.com/mozilla/mozillafestival.org/labels/2018%20CFP%20Close

- [x] Close CFP: Proposals page updates #1019
- [x] Close CFP: Homepage and Spaces page updates #1018 
- [x] Home page: Implement Updates 2018 CFP Close #1007
- [x] Tickets page: Update Content & Push Live #926

### CODE REVIEW

**Comment by sabrinang** [comment]
@mmmavis 
#1018 
- remove proposals from navigation (it is still there)

#962
- Design feedback: Add padding on top of yellow `GET TICKETS` button to balance space with bottom.

#926 Tickets page
- Can buttons have bolder 2px stroke and bold type for `Buy Ticket` (looks like it is in helvetica but check if it is fira sans)

Copy looks good to me and functionality for video and ticket modals are working.

**Comment by mmmavis** [comment]
https://mozillafestival-org-st-pr-1035.herokuapp.com/fringe

> #1018 remove proposals from navigation (it is still there)

Done

> #962 Design feedback: Add padding on top of yellow GET TICKETS button to balance space with bottom.

Top and bottom paddings of the button are actually the same. I'm unable to track down why the text itself comes with more spaces at the bottom. I will fix it if I'm able to find out why but I don't want this to be the blocker for today's push.

> #926 Tickets page - Can buttons have bolder 2px stroke and bold type for Buy Ticket (looks like it is in helvetica but check if it is fira sans)

I'm using existing "btn-primary-outline" style for the "Buy Ticket" button ( also seen on https://mozillafestival-org-st-pr-1035.herokuapp.com/fringe ). Do you want the style changes (bolder 2px stroke and bold type) to be applied to all "btn-primary-outline" buttons on the site or just these ones on the /tickets page?

Can you link me to the design file (.ai? .sketch?) so I can reference to the exact stylings. It's hard for me to tell from flat file especially mockups on Redpen are kinds small. Thanks!

**Comment by mmmavis** [comment]
@sabrinang ^^

**Comment by sabrinang** [comment]
@mmmavis If it is using existing styles let's go with that and not let the design tweaks be a blocker. Thanks for removing proposals from the nav 👍

**Pull request merged**
