### PR TITLE
About page & 'What to Expect' page updates

### PR DESCRIPTION
**Pull request by mmmavis**
# DO NOT MERGE YET (NEED APPROVAL TO GO LIVE)

Related to #1000 , #1001 

- updated About page & moved 'MozFest timeline' to its own component
- updated 'What to Expect' page (it's now called 'Why Come to MozFest' page

### CODE REVIEW

**Comment by mmmavis** [comment]
@sabrinang can you help review the About page and Why Come to MozFest page? I _think_ I captured all the updated copy but it would be great to have someone to review it again.

**Comment by sabrinang** [comment]
@mmmavis Copy matches what I got in mockups (and you fixed MozFest capitalization typo I had in the mockup too) so looking good. Here are some design review feedback:

**About page:**
- On desktop, can you increase the space below the mozfest team section
image
- On mobile, can you reduce type size of description below About MozFest to be body copy size?
image
- On mobile, can you center space icons alignment?
image

**Why Come to MozFest page:**
- On mobile, adjust spacing above and below video to be shorter
image

**Comment by mmmavis** [comment]
@sabrinang can you 👀 again? https://mozillafestival-org-st-pr-1003.herokuapp.com/

One thing I didn't fix

> On mobile, can you reduce type size of description below About MozFest to be body copy size? 

It is already in body copy font size. MozFest site's body copy size is set to `1.2rem`. Let me know how small you want me to adjust it to and whether the change is just for this element or the base body copy size for the site.

**Comment by sabrinang** [comment]
@mmmavis For me it appears to be `22px` but if it is already set `1.2rem` that is ok. The letter-spacing is also a bit wide can we reduce to `letter-spacing: 0.5px;` as this will help with reducing the space.

Also Consuela pointed out a typo to change `Theses` to `These`
image

Note: design mockup issue is closed @consuelamckenzie please view deployment

**Comment by mmmavis** [comment]
@sabrinang Nice catch! I fixed the typo and updated paragraph text size on mobile (you were right. it indeed was 22px) I also updated the base letter spacing in jumbotron section (big hero) to `0.5px`. Just a note that `h1` and `h2` in jumbotron section have their own letter spacing rules. Please file a new ticket if we want to adjust these values as the changes will apply to all these elements across pages on the site.

Can we push this PR live? Or do we need Sarah's approval?

**Comment by sabrinang** [comment]
@mmmavis Thanks for fixing and for letting me know about the jumbotron styles for future revisions. R+ on design review from me.

@Saallen Please review the [deployment](https://mozillafestival-org-st-pr-1003.herokuapp.com/) _About_ page & _What to Expect_ page. PR is ready to go live after your approval.

**Comment by Saallen** [comment]
@mmmavis the sign for updates link at the bottom of the home page links to the tito homepage but also contains all the tickets- this is confusing.
@marcwalsh is investigating whether we can get a direct link that show the tito page with no tickets

Please hold home page but why come is ready to push live

**Comment by mmmavis** [comment]
@Saallen this PR only contains changes to the **About page** and **Why Come to MozFest page**. I didn't change anything on the home page - home page should be the same as what we have live currently https://mozillafestival.org/

**Comment by marcwalsh** [comment]
@Saallen @mmmavis we can use the following link to just have the sign up form:
https://ti.to/mozilla/mozilla-festival-2018/interested_users/new

I've had to change the header for it, which means it's too long to then have on the Ti.To ticketing page. Let me know if this works for you both.

**Comment by marcwalsh** [comment]
The alternative if this isn't working (as there isn't the possibilty of a checkbox for consent). Is that we hvae a form on the website which has it's own privacy guidlines and then we can import that into Ti.To using a CSV.

The CSV format is super simple and just requires column 1 to be the email address and column 2 as the First Name / Full Name. This could then be uploaded weekly.

**Comment by Saallen** [comment]
Ok @mmmavis ignore @marcwalsh and my comments here in relation to aBOUT page and why come to MozFest- approved and please push live

**Comment by mmmavis** [comment]
Cool cool. I will push these changes live next Monday since we wanna avoid pushing code on Fridays.

**Pull request merged**
