### PR TITLE
Updated spaces & sessions page

### LINKED ISSUE #384: Update Spaces & Sessions page
specs are on https://github.com/MozillaFoundation/2016.Mozillafestival.org/issues/17#issuecomment-222814126

> @mmmavis here is the content for this page: https://docs.google.com/document/d/1TyncLzVRiMt-bwAa9aX99oIdG6G6WiDzYupsvYjnIE8/edit#  A few notes:
- This page is now called Spaces and Sessions. Please update the banner text if Ricardo didn't do that already
- You can delete all the space icons for now. We'll add them back in in the fall
- Wranglers are names only (no handles) for now
- Localisation is spelled with an S, not a Z this year (British spelling)

and remove intro paragraph

### PR DESCRIPTION
**Pull request by mmmavis**
Fixes #384 

@edrushka can you review? http://mavis-mozfest.herokuapp.com/spaces-and-sessions (note that this PR doesn't contain Scott's proposal related pages changes)

### CODE REVIEW

**Comment by edrushka** [comment]
Ohh looks beautiful! Nothing is jumping out at me but I can review it again with fresh eyes tomorrow. @Saallen can you take a look as well?

**Comment by Saallen** [comment]
Thanks all- read throught this bright eyed and bushy tailed and spotted some edits
Feedback
- [ ] Do we need to explain what Spaces are?
- [ ] Digital Arts and Cultur- can you capitalise Web?
- [ ] Can we move Eva under Ryan on the Journalism
- [ ] OPen science can you swap Arliss and Kirstys names around?
- [ ] Open Badges- it should be Lucy Neale (just double checking this with Matt )
- [ ] Demystify the web- can you swap around Kim and Roberts name
- [ ] Moz Ex can you capitalise the work Web 
- [ ] @edrushka what do you think of adding  (Art Exhibit)
- [ ] Open badges should be recognise rather than recognize
- [ ] Fuel the movement can you energized to energised
- [ ] Can you swap  the positioning of Melissa and  Georgias

**Comment by edrushka** [comment]
For the Space description, please put:

Spaces are physical and thematic learning hubs based around a broad topic, like science, art, or journalism. A Space is made up of sessions, which are hands-on, educational gatherings based around a specific topic, like “Using Crafts to Teach Localization Processes.” Sessions generally run 30-90 minutes. 

You can put this at the top of the page underneath where it currently says Spaces and Sessions in red.

**Comment by edrushka** [comment]
Please capitalize all instances of Web. I know it looks weird in some cases, but for consistency with our style guide, that's how we need to roll!

**Comment by mmmavis** [comment]
http://mavis-mozfest.herokuapp.com/spaces-and-sessions

> - Moz Ex can you capitalise the work Web 

Are we talking about turning web pages into Web pages?

> - Digital Arts and Cultur- can you capitalise Web?

Are we talking about turning web literacy into Web literacy?

just wanna double check, @edrushka ^

**Comment by edrushka** [comment]
yes and yes!

**Comment by mmmavis** [comment]
oops didn't see https://github.com/mozilla/mozillafestival.org/pull/385#issuecomment-223123670 I'll capitalize all instances of Web

**Comment by edrushka** [comment]
Please make this last minute change to the 'Fuel the Movement' description:

The open Internet movement needs you! When everyday Internet users band together, we can overcome the many threats to the free and open Internet, and keep it a global public resource.

This year, we're focusing on copyright. We believe copyright should foster innovation, creation and competition. Sessions should help participants understand how changes in copyright law in the European Union could impact them through interactive workshops, DIY making, and lightning talks. In the Fuel the Movement Space, we couple fun and creativity with Internet policy and advocacy. Participants will walk away energized and equipped to take advantage of present-day opportunities online.

Have a great session idea? Head to the MozFest Call for Proposals page [link].

**Comment by mmmavis** [comment]
yay, merging! 🎉

**Pull request merged**
