### PR TITLE
Cleaned up header.jsx code so it's not using absolute positioning

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #910 

https://mozillafestival-org-sta-pr-919.herokuapp.com/

### CODE REVIEW

**Comment by mmmavis** [comment]
@sabrinang I cleaned up the nav bar section code so it's not using absolute positioning. This will make the nav bar more flexible and responsive. (e.g., we don't have to add more CSS rules every time we make any changes to the nav bar) I've also made the nav bar use Bootstrap's rows and columns so the new nav bar now looks a bit narrower than before. I don't see it as a big issue. But please let me know if anything needs to be adjusted. My goal is to gradually clean up the CSS code by replacing custom CSS we wrote 2-3 years with Bootstrap classes.

**Comment by mmmavis** [comment]
@sabrinang mind giving this a quick review and approving this if it looks good?

**Comment by sabrinang** [comment]
I like how it looks on desktop and mobile and it is more responsive. There is a breakpoint in between that I'd be great if it just went under the logo, currently it is a pretty tight cluster adjacent to it:  
image

**Comment by mmmavis** [comment]
fixed!

**Pull request merged**
