### PR TITLE
Updated D&D section on home page

### PR DESCRIPTION
**Pull request by mmmavis**
Related to #964

### CODE REVIEW

**Comment by mmmavis** [comment]
@KevZawacki could you check the D&D section on the homepage and see if I got everything right?  https://mozillafestival-org-sta-pr-969.herokuapp.com/ I didn't put "hall of fame" as part of the section header. But do let me know if I should amend that. Thanks!

**Comment by KevZawacki** [comment]
@mmmavis This looks fantastic! 🎆 

Two brief thoughts:

[1] Can we change the "and" in the headline to a "&"? So, "Dialogues & Debates"

[2] For symmetry, do you think we should add a ninth speaker? So we have three rows of three?

If so, I propose we add: Nanjira Sambuli | activist | [Closing the Digital Gender Divide](https://www.youtube.com/watch?v=sECDr9LJlMs&t=0s&list=PLYiaJo7rYNXInD71OAShY4xfl6fhskoUV&index=13)

**Comment by mmmavis** [comment]
@KevZawacki awesome suggestions! Changes have been made - https://mozillafestival-org-sta-pr-969.herokuapp.com/ 👀 ?

**Comment by KevZawacki** [comment]
@mmmavis Perfect!

**Pull request merged**
